# Generated by Django 2.1.5 on 2019-01-22 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, null=True, verbose_name='标题')),
                ('content', models.TextField(null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('key_words', models.CharField(max_length=10, null=True, verbose_name='关键字')),
            ],
            options={
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=10, null=True, verbose_name='栏目')),
                ('nick_name', models.CharField(max_length=20, null=True, verbose_name='别名')),
                ('fid', models.CharField(max_length=20, null=True, verbose_name='父节点')),
                ('keywords', models.CharField(max_length=20, null=True, verbose_name='关键字')),
                ('describe', models.CharField(max_length=100, null=True, verbose_name='描述')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, unique=True, verbose_name='姓名')),
                ('icon', models.ImageField(null=True, upload_to='upload', verbose_name='头像')),
                ('resume', models.CharField(max_length=1000, null=True, verbose_name='个人简介')),
            ],
            options={
                'db_table': 'resume',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, unique=True, verbose_name='姓名')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('icon', models.ImageField(null=True, upload_to='upload', verbose_name='头像')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('operate_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='art', to='users.Category'),
        ),
    ]
